---
title: "Twitter coverage of the Biology of Genomes 2019 conference"
author: "Javier Herrero"
output: 
  html_document: 
    number_sections: yes
    toc: yes
    toc_float: yes
---

```{r knitr, include = FALSE}
DOCNAME <- tools::file_path_sans_ext(knitr::current_input())
knitr::opts_chunk$set(autodep        = TRUE,
                      cache          = FALSE,
                      cache.path     = paste0("cache/", DOCNAME, "/"),
                      cache.comments = TRUE,
                      echo           = FALSE,
                      error          = FALSE,
                      fig.align      = "center",
                      fig.path       = paste0("figures/", DOCNAME, "/"),
                      fig.width      = 10,
                      fig.height     = 8,
                      message        = FALSE,
                      warning        = FALSE)
```


```{r params}
set.seed(1)

hashtag <- "#BoG19"
conf_name <- "Biology of Genomes 2019"
timezone <- "America/New_York"
days <- c("2019-05-07", "2019-05-08", "2019-05-09", "2019-05-10", "2019-05-11")
accent <- "skyblue3"
light_accent <- rgb(t((255 - (255 - col2rgb(accent)[, 1]) / 2)), maxColorValue = 255)
pal <- "Set1"
topics_k <- 6
fixed <- TRUE # Set to TRUE to stop adding new tweets
```


```{r child = "template.Rmd"}
```
